name: Akeyless Local Secret Test

on:
  workflow_dispatch:

jobs:
  akeyless-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get OIDC Token
        run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          JWT=$(echo $OIDC_TOKEN | jq -j '.value')
          echo "JWT=$JWT" >> $GITHUB_ENV # Store the JWT as an environment variable

      - name: Obtain CLI
        id: get-cli
        run: |
          curl -o akeyless https://akeyless-cli.s3.us-east-2.amazonaws.com/cli/latest/production/cli-linux-amd64
          chmod +x akeyless
          ./akeyless --init
          ./akeyless auth --access-type oidc --access-id p-y5bae7zhmim1om --jwt $GITHUB_ENV
          ./akeyless describe-sub-claims
