# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.1.2
        with:
          access-id: <here>
          access-type: jwt        
          dynamic-secrets: |
            - name: "/devops/docker"
              output-name: "docker-dynamic-secret"
      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"

            echo "dynamic secret: ${{ steps.fetch-dynamic-secrets.outputs.docker }}"
            # echo "my_second_secret: ${{ env.my_second_secret }}" >> secrets.txt

