# This is a basic workflow to help you get started with Actions

name: Fetch Secret from US tenant

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:

  build:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-secret
        uses: akeyless-community/akeyless-github-action@v1.1.2
        with:
          api-url: https://api.us.akeyless.io
          access-id: p-y9f5vxy2ajioos
          access-type: jwt        
          static-secrets: |
            - name: "/MyFirstSecret"
              output-name: "secret"
      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"

            echo "Secret: ${{ steps.fetch-secret.outputs.secret }}"
